{"uid":"cf36265b7e7de558","name":"test_network_cut_ip_change_leader_http","fullName":"tests.integration.ha.test_network_cut#test_network_cut_ip_change_leader_http","historyId":"e06f2ad8c13ff7130f4ced0fde0fd459","time":{"start":1728179583590,"stop":1728182726758,"duration":3143168},"status":"broken","statusMessage":"asyncio.exceptions.TimeoutError","statusTrace":"Traceback (most recent call last):\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/juju/utils.py\", line 129, in _block\n    await jasyncio.sleep(wait_period)\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 605, in sleep\n    return await future\nasyncio.exceptions.CancelledError\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 456, in wait_for\n    return fut.result()\nasyncio.exceptions.CancelledError\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: TResult | None = func()\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 242, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 92, in pytest_runtest_call\n    yield from thread_exception_runtest_hook()\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 68, in thread_exception_runtest_hook\n    yield\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 95, in pytest_runtest_call\n    yield from unraisable_exception_runtest_hook()\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 70, in unraisable_exception_runtest_hook\n    yield\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 848, in pytest_runtest_call\n    yield from self._runtest_for(item, \"call\")\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 831, in _runtest_for\n    yield\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/_pytest/capture.py\", line 879, in pytest_runtest_call\n    return (yield)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/_pytest/skipping.py\", line 257, in pytest_runtest_call\n    return (yield)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 174, in pytest_runtest_call\n    item.runtest()\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 1627, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 159, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete\n    return future.result()\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/tests/integration/ha/test_network_cut.py\", line 357, in test_network_cut_ip_change_leader_http\n    await network_cut_leader(ops_test)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/tests/integration/ha/test_network_cut.py\", line 144, in network_cut_leader\n    await ops_test.model.block_until(\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/juju/model.py\", line 1046, in block_until\n    await utils.block_until(done,\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/juju/utils.py\", line 130, in block_until\n    await jasyncio.shield(jasyncio.wait_for(_block(), timeout))\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 458, in wait_for\n    raise exceptions.TimeoutError() from exc\nasyncio.exceptions.TimeoutError","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[{"name":"event_loop","time":{"start":1728178568787,"stop":1728178568788,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"tmp_path_factory","time":{"start":1728178568788,"stop":1728178568788,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"opensearch_sysctl_settings","time":{"start":1728178568788,"stop":1728178568816,"duration":28},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test","time":{"start":1728178568816,"stop":1728178568972,"duration":156},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"abort_on_fail","time":{"start":1728179583589,"stop":1728179583589,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"asyncio.exceptions.TimeoutError","statusTrace":"Traceback (most recent call last):\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/juju/utils.py\", line 129, in _block\n    await jasyncio.sleep(wait_period)\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 605, in sleep\n    return await future\nasyncio.exceptions.CancelledError\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 456, in wait_for\n    return fut.result()\nasyncio.exceptions.CancelledError\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: TResult | None = func()\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 242, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 92, in pytest_runtest_call\n    yield from thread_exception_runtest_hook()\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 68, in thread_exception_runtest_hook\n    yield\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 95, in pytest_runtest_call\n    yield from unraisable_exception_runtest_hook()\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 70, in unraisable_exception_runtest_hook\n    yield\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 848, in pytest_runtest_call\n    yield from self._runtest_for(item, \"call\")\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 831, in _runtest_for\n    yield\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/_pytest/capture.py\", line 879, in pytest_runtest_call\n    return (yield)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/_pytest/skipping.py\", line 257, in pytest_runtest_call\n    return (yield)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 174, in pytest_runtest_call\n    item.runtest()\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 1627, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 159, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete\n    return future.result()\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/tests/integration/ha/test_network_cut.py\", line 357, in test_network_cut_ip_change_leader_http\n    await network_cut_leader(ops_test)\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/tests/integration/ha/test_network_cut.py\", line 144, in network_cut_leader\n    await ops_test.model.block_until(\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/juju/model.py\", line 1046, in block_until\n    await utils.block_until(done,\n  File \"/home/ubuntu/actions-runner/_work/opensearch-dashboards-operator/opensearch-dashboards-operator/.tox/integration/lib/python3.10/site-packages/juju/utils.py\", line 130, in block_until\n    await jasyncio.shield(jasyncio.wait_for(_block(), timeout))\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 458, in wait_for\n    raise exceptions.TimeoutError() from exc\nasyncio.exceptions.TimeoutError","steps":[],"attachments":[{"uid":"7b66765441bfe3e","name":"log","source":"7b66765441bfe3e.txt","type":"text/plain","size":1231},{"uid":"92a251248f99b744","name":"stdout","source":"92a251248f99b744.txt","type":"text/plain","size":74}],"parameters":[],"stepsCount":0,"shouldDisplayMessage":true,"attachmentsCount":2,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"abort_on_fail::0","time":{"start":1728182726763,"stop":1728182726763,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test::finalizer","time":{"start":1728182726783,"stop":1728182727129,"duration":346},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::2","time":{"start":1728182727130,"stop":1728182727130,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_close_event_loop","time":{"start":1728182727130,"stop":1728182727130,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_provide_clean_event_loop","time":{"start":1728182727130,"stop":1728182727130,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"abort_on_fail"},{"name":"tag","value":"group(1)"},{"name":"tag","value":"runner(['self-hosted', 'linux', 'X64', 'jammy', 'large'])"},{"name":"tag","value":"asyncio"},{"name":"parentSuite","value":"tests.integration.ha"},{"name":"suite","value":"test_network_cut"},{"name":"host","value":"github-runner"},{"name":"thread","value":"30122-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.ha.test_network_cut"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"ac5d457a00ceaa9b","status":"unknown","time":{}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":1,"skipped":27,"passed":32,"unknown":1,"total":61},"items":[{"uid":"b6a042659744d8df","reportUrl":"../1204//#testresult/b6a042659744d8df","status":"passed","time":{"start":1728093100301,"stop":1728093894464,"duration":794163}},{"uid":"7fb7132aadbfc1eb","reportUrl":"../1201//#testresult/7fb7132aadbfc1eb","status":"passed","time":{"start":1728006544225,"stop":1728007460899,"duration":916674}},{"uid":"3305e41c7f6acb60","reportUrl":"../1187//#testresult/3305e41c7f6acb60","status":"skipped","statusDetails":"XFAIL reason: aborted\n\n_pytest.outcomes.XFailed: aborted","time":{"start":1727920759637,"stop":1727920759637,"duration":0}},{"uid":"55fdc1ec8c4281be","reportUrl":"../1182//#testresult/55fdc1ec8c4281be","status":"passed","time":{"start":1727834215422,"stop":1727834889381,"duration":673959}},{"uid":"d28210398ce49a09","reportUrl":"../1181//#testresult/d28210398ce49a09","status":"passed","time":{"start":1727747131548,"stop":1727747372352,"duration":240804}},{"uid":"4923592b8dfef744","reportUrl":"../1174//#testresult/4923592b8dfef744","status":"passed","time":{"start":1727660480392,"stop":1727660923504,"duration":443112}},{"uid":"87a081c1ace871af","reportUrl":"../1173//#testresult/87a081c1ace871af","status":"passed","time":{"start":1727574180344,"stop":1727574445423,"duration":265079}},{"uid":"ff18ee6c4602b977","reportUrl":"../1172//#testresult/ff18ee6c4602b977","status":"passed","time":{"start":1727487727323,"stop":1727488010356,"duration":283033}},{"uid":"bae4d08ebdda2cac","reportUrl":"../1171//#testresult/bae4d08ebdda2cac","status":"passed","time":{"start":1727401048388,"stop":1727401481804,"duration":433416}},{"uid":"bc27722c17e5cefd","reportUrl":"../1165//#testresult/bc27722c17e5cefd","status":"passed","time":{"start":1727314570269,"stop":1727315033549,"duration":463280}},{"uid":"de8863b342aefa70","reportUrl":"../1158//#testresult/de8863b342aefa70","status":"passed","time":{"start":1727228195573,"stop":1727228657936,"duration":462363}},{"uid":"c1fe300caf88728f","reportUrl":"../1152//#testresult/c1fe300caf88728f","status":"passed","time":{"start":1727141824085,"stop":1727142226758,"duration":402673}},{"uid":"9348049302108091","reportUrl":"../1141//#testresult/9348049302108091","status":"passed","time":{"start":1727055427817,"stop":1727055860877,"duration":433060}},{"uid":"1370ada82889d766","reportUrl":"../1138//#testresult/1370ada82889d766","status":"passed","time":{"start":1726969090272,"stop":1726969523770,"duration":433498}},{"uid":"6f2a8e59eba95a3c","reportUrl":"../1137//#testresult/6f2a8e59eba95a3c","status":"passed","time":{"start":1726882739660,"stop":1726883081659,"duration":341999}},{"uid":"81835ea7fb44d364","reportUrl":"../1131//#testresult/81835ea7fb44d364","status":"passed","time":{"start":1726796986240,"stop":1726797662826,"duration":676586}},{"uid":"d2df41fb0b336aa8","reportUrl":"../1127//#testresult/d2df41fb0b336aa8","status":"passed","time":{"start":1726710569582,"stop":1726711456202,"duration":886620}},{"uid":"6b9f42e1585f77c0","reportUrl":"../1126//#testresult/6b9f42e1585f77c0","status":"passed","time":{"start":1726623461368,"stop":1726623893225,"duration":431857}},{"uid":"9342431c27bebc36","reportUrl":"../1124//#testresult/9342431c27bebc36","status":"passed","time":{"start":1726536972772,"stop":1726537434992,"duration":462220}},{"uid":"f42324ac283077a5","reportUrl":"../1122//#testresult/f42324ac283077a5","status":"passed","time":{"start":1726450876663,"stop":1726451159111,"duration":282448}}]},"tags":["runner(['self-hosted', 'linux', 'X64', 'jammy', 'large'])","asyncio","abort_on_fail","group(1)"]},"source":"cf36265b7e7de558.json","parameterValues":[]}